server:
  port: 8092

spring:
  application:
    name: xuyou-user

  config:
    import:
      - application-common.yml
      - application-xuyou.yml
      - application-druid.yml
      - application-mybatis-plus.yml
      - application-devtools.yml
      - application-logging.yml
      - application-snowflake.yml
      - application-jackson.yml
      - application-servlet.yml
      - application-doc.yml
      - application-rabbitmq.yml
      - application-redis.yml
      - application-jwt.yml

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
