# Redis配置
spring:
  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1小时
      cache-null-values: true
  data:
    redis:
      host: api.xiaomizha.ltd
      port: 6379
      password: 131415
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 3000ms

  # Redisson配置
  redis:
    redisson:
      config:
        singleServerConfig:
          address: "redis://api.xiaomizha.ltd:6379"
          password: "131415"
          database: 0
          connectionMinimumIdleSize: 5
          connectionPoolSize: 20
          connectTimeout: 3000
          timeout: 3000
