# MyBatis Plus配置
mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  mapper-locations:
    - classpath*:/mapper/**/*.xml
    - classpath*:/mapper/*.xml
  # 实体扫描, 多个package用逗号或者分号分隔
  type-aliases-package: ltd.xiaomizha.xuyou
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型
      id-type: assign_id
      # 字段策略 NOT_NULL:"非 NULL 判断",NOT_EMPTY:"非空判断"
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_empty
      # 驼峰下划线转换
      table-underline: true
      # 是否开启大写命名
      capital-mode: false
      # 逻辑删除配置
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: true
    # 懒加载
    aggressive-lazy-loading: true
    lazy-loading-enabled: true
    # MyBatis 自动映射策略
    auto-mapping-behavior: partial
    # MyBatis 自动映射时未知列或未知属性处理策略
    auto-mapping-unknown-column-behavior: none
    # 打印查询语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 枚举处理
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

